{"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/56", "repository_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning", "labels_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/56/labels{/name}", "comments_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/56/comments", "events_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/56/events", "html_url": "https://github.com/PyTorchLightning/pytorch-lightning/issues/56", "id": 477880521, "node_id": "MDU6SXNzdWU0Nzc4ODA1MjE=", "number": 56, "title": "pip installation using github repository incomplete", "user": {"login": "immanuelweber", "id": 1731035, "node_id": "MDQ6VXNlcjE3MzEwMzU=", "avatar_url": "https://avatars.githubusercontent.com/u/1731035?v=4", "gravatar_id": "", "url": "https://api.github.com/users/immanuelweber", "html_url": "https://github.com/immanuelweber", "followers_url": "https://api.github.com/users/immanuelweber/followers", "following_url": "https://api.github.com/users/immanuelweber/following{/other_user}", "gists_url": "https://api.github.com/users/immanuelweber/gists{/gist_id}", "starred_url": "https://api.github.com/users/immanuelweber/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/immanuelweber/subscriptions", "organizations_url": "https://api.github.com/users/immanuelweber/orgs", "repos_url": "https://api.github.com/users/immanuelweber/repos", "events_url": "https://api.github.com/users/immanuelweber/events{/privacy}", "received_events_url": "https://api.github.com/users/immanuelweber/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 19, "created_at": "2019-08-07T11:50:31Z", "updated_at": "2019-08-08T09:28:35Z", "closed_at": "2019-08-08T09:28:35Z", "author_association": "NONE", "active_lock_reason": null, "body": "I tried to install pytorch-lightning using pip and the github repository.\r\nImporting the module results in the following errors:\r\n\r\n`\r\nModuleNotFoundError                       Traceback (most recent call last)\r\n<ipython-input-4-942bf9f93773> in <module>\r\n      8 from torchvision import ops\r\n      9 \r\n---> 10 import pytorch_lightning as ptl\r\n     11 from pytorch_lightning import Trainer\r\n     12 from test_tube import Experiment\r\n\r\n/opt/miniconda3/envs/dev_pytorch_lightning36/lib/python3.6/site-packages/pytorch_lightning/__init__.py in <module>\r\n----> 1 from .models.trainer import Trainer\r\n      2 from .root_module.root_module import LightningModule\r\n      3 from .root_module.decorators import data_loader\r\n\r\nModuleNotFoundError: No module named 'pytorch_lightning.models'`\r\n\r\nFollowing the error I found out, that there is no `models` folder under the path `site-packages\\pytorch_lightning` ", "closed_by": {"login": "immanuelweber", "id": 1731035, "node_id": "MDQ6VXNlcjE3MzEwMzU=", "avatar_url": "https://avatars.githubusercontent.com/u/1731035?v=4", "gravatar_id": "", "url": "https://api.github.com/users/immanuelweber", "html_url": "https://github.com/immanuelweber", "followers_url": "https://api.github.com/users/immanuelweber/followers", "following_url": "https://api.github.com/users/immanuelweber/following{/other_user}", "gists_url": "https://api.github.com/users/immanuelweber/gists{/gist_id}", "starred_url": "https://api.github.com/users/immanuelweber/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/immanuelweber/subscriptions", "organizations_url": "https://api.github.com/users/immanuelweber/orgs", "repos_url": "https://api.github.com/users/immanuelweber/repos", "events_url": "https://api.github.com/users/immanuelweber/events{/privacy}", "received_events_url": "https://api.github.com/users/immanuelweber/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/56/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/56/timeline", "performed_via_github_app": null}