{"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/41", "repository_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning", "labels_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/41/comments", "events_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/41/events", "html_url": "https://github.com/PyTorchLightning/pytorch-lightning/issues/41", "id": 476964011, "node_id": "MDU6SXNzdWU0NzY5NjQwMTE=", "number": 41, "title": "Unable to import trainer", "user": {"login": "sameerIISc", "id": 42006002, "node_id": "MDQ6VXNlcjQyMDA2MDAy", "avatar_url": "https://avatars.githubusercontent.com/u/42006002?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sameerIISc", "html_url": "https://github.com/sameerIISc", "followers_url": "https://api.github.com/users/sameerIISc/followers", "following_url": "https://api.github.com/users/sameerIISc/following{/other_user}", "gists_url": "https://api.github.com/users/sameerIISc/gists{/gist_id}", "starred_url": "https://api.github.com/users/sameerIISc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sameerIISc/subscriptions", "organizations_url": "https://api.github.com/users/sameerIISc/orgs", "repos_url": "https://api.github.com/users/sameerIISc/repos", "events_url": "https://api.github.com/users/sameerIISc/events{/privacy}", "received_events_url": "https://api.github.com/users/sameerIISc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2019-08-05T17:01:10Z", "updated_at": "2019-08-05T18:46:59Z", "closed_at": "2019-08-05T17:47:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hey, I am able to import pytorch_lightning but not the trainer. I am new to python and have no idea how to deal with it. It throws following error:\r\n\r\n  File \"<stdin>\", line 1, in <module>\r\nImportError: cannot import name Trainer\r\n\r\nThanks", "closed_by": {"login": "williamFalcon", "id": 3640001, "node_id": "MDQ6VXNlcjM2NDAwMDE=", "avatar_url": "https://avatars.githubusercontent.com/u/3640001?v=4", "gravatar_id": "", "url": "https://api.github.com/users/williamFalcon", "html_url": "https://github.com/williamFalcon", "followers_url": "https://api.github.com/users/williamFalcon/followers", "following_url": "https://api.github.com/users/williamFalcon/following{/other_user}", "gists_url": "https://api.github.com/users/williamFalcon/gists{/gist_id}", "starred_url": "https://api.github.com/users/williamFalcon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/williamFalcon/subscriptions", "organizations_url": "https://api.github.com/users/williamFalcon/orgs", "repos_url": "https://api.github.com/users/williamFalcon/repos", "events_url": "https://api.github.com/users/williamFalcon/events{/privacy}", "received_events_url": "https://api.github.com/users/williamFalcon/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/41/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/PyTorchLightning/pytorch-lightning/issues/41/timeline", "performed_via_github_app": null}